@startjson

title JSON Data

{ "admistrator":
		{
			"database": {
        "ddataK": "Phython_10",
        "ddataB": "ДСТУ 2282-93 Система стандартів безпеки праці. Устаткування технологічне для виробництва твердих сирів. Вимоги безпеки",
        "kursInfo":{
          "kabout":"Курс Python дасть вам не лише основні навички, необхідні для роботи. Ми готуємо вас до повноцінного входу до професії IT-фахівця.",
          "kprice": "26200"
        },
        "bezpekaInfo":{
          "bdocuments":" Устаткування технологічне для виготовлення твердих сирів"
        }
      }
		}
}

@endjson
