@startuml

title Conditional - Activity Diagram measurements() 

start

:ПП аналізує дані про курс;


if (Представник ІТ-школи додав опис курсу?) then (так)
  if (Представник ІТ-школи вказав ціну курсу?) then (так)
    : Інформація про курс оублікована!;
  else (ні)
    : Помилка: Укажіть вартість курсу!;
  endif
else (ні)
  :Помилка: Додайте опис курсу!;
endif

stop

@enduml
