name: TestCases
on: push

jobs:
  test-cases:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    - name: Compile & Execute
      run: |
        pip install pytest
        pytest TestCases.py
